compilarEscritura: escritura.c
	gcc escritura.c -o escritura

compilarLectura: lectura.c
	gcc lectura.c -o lectura

ejecutarEscritura: compilarEscritura escritura
	./escritura

ejecutarLectura: compilarLectura lectura
	./lectura